[build]
  base = "/"
  publish = "out" # Adjust this to your build output directory (e.g., "out" for Next.js)
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20" # Use the Node.js version compatible with your project

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = [
        "node_modules/.cache", # Cache Next.js build files
        "node_modules" # Cache dependencies
      ]


