[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18", NEXT_USE_NETLIFY_EDGE = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.cache]
  paths = [
    "node_modules",
    ".next/cache"
  ]

